### ISSUE TITLE
USB breaks when ADB is enabled

### ISSUE THREAD

**Issue by dgadelha** [artefvck/artefvck#2]
The USB subsystem appears to stop if you enable ADB.
Although, if you disable ADB and keep only MTP, it will work.
I think it's something with idVendor and idProduct
This is how it should appear on setting mtp,adb
Bus 002 Device 080: ID 0b05:5481 ASUSTek Computer, Inc.
(and it doesn't).
This should affect branches master, development, cm-13.0 and cm-13.0-A500CG

**Comment by artefvck** [comment]
adb enable for our init , properties interest

**Comment by dgadelha** [comment]
My ramdisk has a property to enable ADB, I also tried to manually start adbd.
The issue is on USB driver, kernel-level.

**Comment by artefvck** [comment]
this is not the issue

I use based on linux stable

I think the problem comes from your own; I use udev or windows work fine

**Comment by dgadelha** [comment]
No it doesn't.
I'm on Ubuntu 15.04 and it does work with any other kernel.
The issue affects kernel from branches `master` and `development`, that, when you enable ADB, it completly stops the USB driver (even MTP, appears like the device was disconnected from USB), but when you set MTP only, it works (device shows up)

**Comment by artefvck** [comment]
My build-13.0 cm with this, there is no problem: P

maybe just because marshmallow

**Comment by dgadelha** [comment]
I tried using the `master` and `development` branches on Lollipop and I got this issue.
Can you check it?
